### ISSUE TITLE
Query without helpers

### ISSUE THREAD

**Issue by acegilz** [danieledangeli/betfair-php#13]
Was trying to follow your instructions to contact directly with betfair API (specifically to try putting a bet =>  https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/PHP) but I couldn't conclude it because of the lack of info on your "Query the Betfair API without the helpers" section.

Thanks

**Comment by idchlife** [comment]
@acegilz 

I assume such requests will look like this:

```
$eventTypes = $betfair->api(Param::create()->setMarketFilter(
    MarketFilter::create()
), 'listEventTypes');
```

If you look into parameters and methods at api.developer.betfair.com you will notice similar classes and parameters in this library.

**Comment by acegilz** [comment]
The problem I am having is exactly in building the parameters since i am always getting similar errors to this all the time: <br />
`<b>Catchable fatal error</b>:  Argument 1 passed to Insert::api() must be an instance of ParamInterface, string given, called in /Applications/XAMPP/xamppfiles/htdocs/bf/time3.php on line 47 and defined in <b>/Applications/XAMPP/xamppfiles/htdocs/bf/time3.php</b> on line <b>14</b><br />`

If someone can provide me a sample example of how to place bets I would really appreciate.

**Comment by idchlife** [comment]
@acegilz I did not yet place bets, but I can say that you are using not Param::create() but string.
Could you provide some code, which caused this error? (time3.php lines 14, 47)

**Comment by acegilz** [comment]
OK. I have made some changes I am having this now:

'<b>Fatal error</b>:  Class 'Param' not found in <b>/Applications/XAMPP/xamppfiles/htdocs/bf/time3.php</b> on line <b>33</b><br />'

with:

'<?php
header('Content-Type: application/json');

use Betfair\BetfairFactory;
use Betfair\Model\MarketFilter;
use Betfair\Model\PriceProjection;

use GuzzleHttp\Ring\Exception\ConnectException;

require 'vendor/autoload.php';

$betfair = BetfairFactory::createBetfair('key', 'username', 'pass');

$a = '1.118379073';
$b = 'LAY';
$c = '1';
$d = '2.22';
$e = '1.01';

$params = '{"marketId":"' . $a . '",
          "instructions":
               [{"selectionId":"' . $c . '",
                 "handicap":"0",
                 "side":"BACK",
                 "orderType":
                 "LIMIT",
                 "limitOrder":{"size":"2",
                              "price":"1000",
                              "persistenceType":"LAPSE"}
                 }], "customerRef":"fsdf"}';

$eventTypes = $betfair->api(Param::create()->setMarketFilter(MarketFilter::create($params)), 'placeOrders');

?>'

**Comment by acegilz** [comment]
sorry the noobness but i have no idea how to handle the params on this

**Comment by idchlife** [comment]
@acegilz you need to add

```
use Betfair\Model\Param;
```

where your use statements are. Also, you are creating setting your params as string, but I suggest you using array syntax and then using json_encode. BUT, that is not the case. (it's just the tip on using PHP)

Ok we need @danieledangeli to provide us some updates on his work progress here.

He said not long ago, that he is working now on placing orders, and also this is the top priority task in todo in readme.

How you theoretically can solve this issue, using dynamically set public properties in Param (after all, jsonSerialize here just uses all properties)

Add your parameters like this:

```
$params = Param::create();
$params->marketId = $a;
$params->instructions = [['selectionId': $c, 'whatever': $b]];
$params->customerRef = 'fdsdf';

$placeOrders = $betfair->api($params, 'placeOrders');
```

**Comment by acegilz** [comment]
Almost there :)

'{"jsonrpc":"2.0","error":{"code":-32602,"message":"DSC-0018"},"id":1}<br />
<b>Notice</b>:  Undefined index: result in <b>/Applications/XAMPP/xamppfiles/htdocs/bf/vendor/erlangb/betfair/src/Betfair/Adapter/ArrayRpcAdapter.php</b> on line <b>18</b><br />'

Being DSC-0018 : A parameter marked as mandatory was not provided (https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Common+Error+Codes)

CODE:

'<?php
header('Content-Type: application/json');

use Betfair\BetfairFactory;
use Betfair\Model\MarketFilter;
use Betfair\Model\PriceProjection;
use Betfair\Model\Param;

use GuzzleHttp\Ring\Exception\ConnectException;

require 'vendor/autoload.php';

$betfair = BetfairFactory::createBetfair('key', 'user', 'pass');

$a = '1.118379073';
$b = 'LAY';
$c = '1';
$d = '2.22';
$e = '1.01';

$params = Param::create();
$params->marketId = $a;
$params->instructions = ['selectionId' => $c, 'handicap' => '0', 'side' => 'BACK', 'orderType' => 'LIMIT', 'limitOrder' => ['size'  => '2', 'price' => '1000', 'persistenceType' =>'LAPSE']];
$params->customerRef = 'fdsdf';

$placeOrders = $betfair->api($params, 'placeOrders');

?>'

**Comment by idchlife** [comment]
@acegilz instructions should be array of associative arrays.
So wrap it up once more in [];

**Comment by acegilz** [comment]
https://www.dropbox.com/s/bhl42ka5xmrh7yg/Captura%20de%20tela%202015-04-28%2014.55.24.png?dl=0

<?php
header('Content-Type: application/json');

use Betfair\BetfairFactory;
use Betfair\Model\MarketFilter;
use Betfair\Model\PriceProjection;
use Betfair\Model\Param;

use GuzzleHttp\Ring\Exception\ConnectException;

require 'vendor/autoload.php';

$betfair = BetfairFactory::createBetfair('key', 'usr', 'pass');

$a = '1.118379073';
$b = 'LAY';
$c = '1';
$d = '2.22';
$e = '1.01';

$p = $a;
$i = [['selectionId' => $c, 'handicap' => '0', 'side' => 'BACK', 'orderType' => 'LIMIT', 'limitOrder' => ['size'  => '2', 'price' => '1000', 'persistenceType' =>'LAPSE']]];

$hash_p = json_encode($p);
$hash_i = json_encode($i);
$hash_c = json_encode('fdsdf');

$params = Param::create();
$params->marketId = $hash_p;
$params->instructions = $hash_i;
$params->customerRef = $hash_c;

$send = json_encode($params);
print_r($params);

$placeOrders = $betfair->api($params, 'placeOrders');

?>

**Comment by idchlife** [comment]
@acegilz previous code with fix:

```
    $a = '1.118379073';
    $b = 'LAY';
    $c = '1';
    $d = '2.22';
    $e = '1.01';

    $params = Param::create();
    $params->marketId = $a;
    $params->instructions = [['selectionId' => $c, 'handicap' => '0', 'side' => 'BACK', 'orderType' => 'LIMIT', 'limitOrder' => ['size' => '2', 'price' => '1000', 'persistenceType' =>'LAPSE']]];
    $params->customerRef = 'fdsdf';

    $placeOrders = $betfair->api($params, 'placeOrders');

    dump($placeOrders);
```

Result:

```
array:5 [▼
  "customerRef" => "fdsdf"
  "status" => "FAILURE"
  "errorCode" => "BET_ACTION_ERROR"
  "marketId" => "1.118379073"
  "instructionReports" => array:1 [▼
    0 => array:3 [▼
      "status" => "FAILURE"
      "errorCode" => "INVALID_BET_SIZE"
      "instruction" => array:5 [▼
        "selectionId" => 1
        "handicap" => 0.0
        "limitOrder" => array:3 [▼
          "size" => 2.0
          "price" => 1000.0
          "persistenceType" => "LAPSE"
        ]
        "orderType" => "LIMIT"
        "side" => "BACK"
      ]
    ]
  ]
]
```

So check everything again. Should be ok. Api and code works.

**Comment by acegilz** [comment]
It worked.

Thank you so much!

**Comment by danieledangeli** [comment]
Hi. I m out till the next Tuesday. Hope can I help soon as possible. I'll create helpers to make easy to code the ability to place bets. Meanwhile I hope you can solve with some workaround. Thanks!

**Comment by acegilz** [comment]
Nooo. Not yet. I tried that code and with the wrong selectionid it displays that error. If we put any numeric or the team name (i have not understand yet what is selectionid) it shows the classic

'{"jsonrpc":"2.0","error":{"code":-32602,"message":"DSC-0018"},"id":1}<br />
<b>Notice</b>:  Undefined index: result in <b>/Applications/XAMPP/xamppfiles/htdocs/bf/vendor/erlangb/betfair/src/Betfair/Adapter/ArrayRpcAdapter.php</b> on line <b>18</b><br />'

**Comment by acegilz** [comment]
ohh come on never mind.... selection id.

THANK YOU :)
