### ISSUE TITLE
Error during credentials verification.

### ISSUE THREAD

**Issue by apuestaya** [danieledangeli/betfair-php#16]
Hello Dear Daniel. I'm having this issue, how can i solve this. Thank you in advance.

https://scrutinizer-ci.com/g/danieledangeli/betfair-php/issues/master/files/src/Betfair/Client/BetfairClient.php?orderField=path&order=asc

**Comment by apuestaya** [comment]
This is error that i'm getting in this issue
[error] => BETTING_RESTRICTED_LOCATION

Server is located in United States.

**Comment by danieledangeli** [comment]
Hey @apuestaya I will check it but I'm pretty sure that the problem is related to your location. Not sure if a server from United States can use the UK endpoints. Try to use a VPN or a EU server to checks if you have this error again
