### ISSUE TITLE
Get the score

### ISSUE THREAD

**Issue by pedroloureiro82** [danieledangeli/betfair-php#17]
Hi. Is there a method to get the score of a in play event ?

For example the live score of soccer game?

Thank you

**Comment by danieledangeli** [comment]
@pedrogrou I'm not sure, but I think that Betfair doesn't provide the scores.
If yes, let me know and I can figure out an implementation for that.
If not, I was studying some times ago some API which provide the scores for free. My idea (in a long term) is to built a service which provide APIs for score and odds.
