### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by acegilz** [danieledangeli/betfair-php#20]
My server is on a blocked location and I need to use a VPN to change the entire server network just to access betfair, it would be cool to implement a proxy on future versions.

**Comment by danieledangeli** [comment]
Hello @acegilz,

have you got any idea how to implement it?

**Comment by acegilz** [comment]
I was not able to do this.

Still using openvpn to change the whole network!

**Comment by danieledangeli** [comment]
@acegilz I think this is the only way 👍 
A proxy could be implemented in some UK location, but i think it shouldn't be a our responsibility.
At very least what you can do is to use your client in some UK servers!
If you don't mind, I'm going to close this issue.
